version: "3.7"
services:
  lido-depositor-bot:
    image: lidofinance/delegator-bot
    build: .
    container_name: lido-delegator-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9000:8080
    environment:
      - NETWORK=${NETWORK}
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - CREATE_TRANSACTIONS=true
    entrypoint: brownie
    command: run delegator

  lido-pause-bot:
    image: lidofinance/delegator-bot
    build: .
    container_name: lido-distributor-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9001:8080
    environment:
      - NETWORK=${NETWORK}
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - DISTRIBUTE_CYCLE=84600
      - CREATE_TRANSACTIONS=true
    entrypoint: brownie
    command: run distributor
