version: "3.7"
services:
  polygon-lido-depositor-bot:
    image: polygonlidofinance/depositor-bot
    build: .
    container_name: polygon-lido-depositor-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9000:8080
    environment:
      - NETWORK=${NETWORK}
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
      - DISTRIBUTE_REWARDS_MAX_GAS_FEE=${DISTRIBUTE_REWARDS_MAX_GAS_FEE}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - CYCLE=${CYCLE}
      - MAX_RATIO=${MAX_RATIO}
      - MIN_RATIO=${MIN_RATIO}
      - PRIORITY_FEE=${PRIORITY_FEE}
      - CONTRACT_GAS_LIMIT=${CONTRACT_GAS_LIMIT}
      - CREATE_TRANSACTIONS=true
      - GAS_FEE_PERCENTILE_1=${GAS_FEE_PERCENTILE_1}
      - GAS_FEE_PERCENTILE_DAYS_HISTORY_1=${GAS_FEE_PERCENTILE_DAYS_HISTORY_1}
      - GAS_FEE_PERCENTILE_2=${GAS_FEE_PERCENTILE_2}
      - GAS_FEE_PERCENTILE_DAYS_HISTORY_2=${GAS_FEE_PERCENTILE_DAYS_HISTORY_2}
      - MAX_GAS_FEE=${MAX_GAS_FEE}
      - GAS_PRIORITY_FEE_PERCENTILE=${GAS_PRIORITY_FEE_PERCENTILE}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    entrypoint: brownie
    command: run depositor
