version: "3.7"
services:
  lido-depositor-bot:
    image: lidofinance/depositor-bot
    build: .
    container_name: lido-depositor-bot
    restart: unless-stopped
    ports:
      - 127.0.0.1:9000:8080
    environment:
      - NETWORK=${NETWORK}
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - CYCLE=${CYCLE}
      - CREATE_TRANSACTIONS=true
    entrypoint: brownie
    command: run depositor
