ssh -p $SSH_PORT -T $SSH_USER@$SSH_HOST <<EOA

ssh -T $SSH_NESTED_HOST <<EOB

cd /srv/depositor-bot

git fetch
git checkout $CIRCLE_BRANCH
git pull

echo "NETWORK=$NETWORK" > .env
echo "WEB3_INFURA_PROJECT_ID=$WEB3_INFURA_PROJECT_ID" >> .env
echo "MAX_GAS_FEE=$MAX_GAS_FEE" >> .env
echo "GAS_FEE_PERCENTILE_1=$GAS_FEE_PERCENTILE_1" >> .env
echo "GAS_FEE_PERCENTILE_DAYS_HISTORY_1=$GAS_FEE_PERCENTILE_DAYS_HISTORY_1" >> .env
echo "GAS_FEE_PERCENTILE_2=$GAS_FEE_PERCENTILE_2" >> .env
echo "GAS_FEE_PERCENTILE_DAYS_HISTORY_2=$GAS_FEE_PERCENTILE_DAYS_HISTORY_2" >> .env
echo "GAS_PRIORITY_FEE_PERCENTILE=$GAS_PRIORITY_FEE_PERCENTILE" >> .env
echo "CONTRACT_GAS_LIMIT=$CONTRACT_GAS_LIMIT" >> .env
echo "WALLET_PRIVATE_KEY=$WALLET_PRIVATE_KEY" >> .env
echo "CREATE_TRANSACTIONS=$CREATE_TRANSACTIONS" >> .env
echo "CYCLE=$CYCLE" >> .env
echo "MIN_RATIO=$MIN_RATIO" >> .env
echo "MAX_RATIO=$MAX_RATIO" >> .env

docker-compose build
docker-compose up -d

EOB

EOA