name: CI Build prod image

on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - "*"
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      